downUnderCTF/grades/grades_grades_grades/src/__init__.py
from flask import Flask
from src.routes import api
from src import auth

def create_app():
    app = Flask(__name__)
    app.auth = auth
    app.register_blueprint(api)
    return app

downUnderCTF/grades/grades_grades_grades/src/auth.py
import jwt
from flask import request, jsonify, current_app, make_response
from functools import wraps
import secrets

SECRET_KEY = secrets.token_hex(32)

def create_token(data):
    token = jwt.encode(data, SECRET_KEY, algorithm='HS256')
    return token

def token_value(token):
    decoded_token = jwt.decode(token, SECRET_KEY, algorithms=['HS256'])
    return decoded_token['stu_num'], decoded_token['stu_email'], decoded_token.get('is_teacher', False)

def decode_token(token):
    try:
        return jwt.decode(token, SECRET_KEY, algorithms=['HS256'])
    except jwt.ExpiredSignatureError:
        return None

def is_teacher_role():
    # if user isn't authed at all
    if 'auth_token' not in request.cookies:
        return False
    token = request.cookies.get('auth_token')
    try:
        data = decode_token(token)
        if data.get('is_teacher', False):
            return True
    except jwt.DecodeError:
        return False
    return False 


def is_authenticated():
    # if user isn't authed at all
    if 'auth_token' not in request.cookies:
        return False

    token = request.cookies.get('auth_token')
    
    try:
        if jwt.decode(token, SECRET_KEY, algorithms=['HS256']) is not None:
            return True
    except jwt.DecodeError:
        return False
    return False 

def requires_teacher(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        token = request.cookies.get('auth_token')
        if not token:
            return jsonify({'message': 'Token is missing'}), 401
        try:
            data = decode_token(token)
            if data is None or data.get("is_teacher") is None:
                return jsonify({'message': 'Invalid token'}), 401
            if data['is_teacher']:
                request.user_data = data
            else:
                return jsonify({'message': 'Invalid token'}), 401
        except jwt.DecodeError:
            return jsonify({'message': 'Invalid token'}), 401

        return f(*args, **kwargs)

    return decorated

def requires_token(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        token = request.cookies.get('auth_token')
        if not token:
            return jsonify({'message': 'Token is missing'}), 401

        try:
            data = decode_token(token)
            if data is None:
                return jsonify({'message': 'Invalid token'}), 401
            request.user_data = data
        except jwt.DecodeError:
            return jsonify({'message': 'Invalid token'}), 401

        return f(*args, **kwargs)

    return decorated

downUnderCTF/grades/grades_grades_grades/src/routes.py
from flask import request, jsonify, Blueprint, current_app, make_response, render_template, redirect, url_for
from src.auth import requires_token, is_authenticated, token_value, requires_teacher, is_teacher_role
import random

api = Blueprint('api', __name__)

def ran_g():
    grades = ['A', 'B', 'C', 'D', 'E', 'F']
    return random.choice(grades)

@api.route('/')
def index():
    if is_teacher_role():
        return render_template('public.html', is_auth=True, is_teacher_role=True)
    elif is_authenticated():
        return render_template('public.html', is_auth=True)
    return render_template('public.html')

@api.route('/signup', methods=('POST', 'GET'))
def signup():

    # make sure user isn't authenticated
    if is_teacher_role():
        return render_template('public.html', is_auth=True, is_teacher_role=True)
    elif is_authenticated():
        return render_template('public.html', is_auth=True)

    # get form data
    if request.method == 'POST':
        jwt_data = request.form.to_dict()
        jwt_cookie = current_app.auth.create_token(jwt_data)
        if is_teacher_role():
            response = make_response(redirect(url_for('api.index', is_auth=True, is_teacher_role=True)))
        else:
            response = make_response(redirect(url_for('api.index', is_auth=True)))
        
        response.set_cookie('auth_token', jwt_cookie, httponly=True)
        return response

    return render_template('signup.html')

@api.route('/grades')
@requires_token
def grades():
    token = request.cookies.get('auth_token')
    number, email, role_bool = token_value(token)
    role = "Student" if not role_bool else "Teacher"
    if is_teacher_role():
        return render_template('grades.html', is_auth=True, number=number, email=email, role=role, mg=ran_g(), eg=ran_g(), sg=ran_g(), gg=ran_g(), ag=ran_g(), is_teacher_role=True)
    return render_template('grades.html', is_auth=True, number=number, email=email, role=role, mg=ran_g(), eg=ran_g(), sg=ran_g(), gg=ran_g(), ag=ran_g())

@api.route('/grades_flag', methods=('GET',))
@requires_teacher
def flag():
    return render_template('flag.html', flag="FAKE{real_flag_is_on_the_server}", is_auth=True, is_teacher_role=True)

@api.route('/logout')
def logout():
    response = make_response(redirect(url_for('api.index')))
    response.delete_cookie('auth_token')
    return response

downUnderCTF/grades/grades_grades_grades/src/templates/base.html
<!DOCTYPE html>
<!-- this is used as the base holding the navbar and bootstrap fuck with this and I'll kill you -->

<style>
    .right-item {
        list-style-type: none;
    }

    html, body {
        margin: 0px;
        padding: 0px;
    }

</style>

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <title>View Assignment Marks</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/lux/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-hVpXlpdRmJ+uXGwD5W6HZMnR9ENcKVRn855pPbuI/mwPIEKAuKgTKgGksVGmlAvt" crossorigin="anonymous">

</head>
<body>
<app-root></app-root>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/">Assignment Grades</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav ml-md-auto d-block d-sm-flex d-md-flex">
            {% if is_teacher_role == true %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('api.flag') }}">Grading Tool</a>
                </li>
            {% endif %}
            {% if is_auth == true %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('api.grades') }}">Grades</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('api.logout') }}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('api.signup') }}">Sign Up</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<article id="container">
    {% block body %}
        // Content will be here
    {% endblock %}
</article>
</body>
</html>

downUnderCTF/grades/grades_grades_grades/src/templates/flag.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .top {
            top: 0;
            text-align: center;
            padding-left:  30px;
            padding-top: 40px;
            padding-bottom: 30px;
            padding-right:  30px;
        }

        .h1 {
            font-size: 60px;
            margin-bottom: 60px;
        }

        .user_info {
            font-size:18px;
            padding-left: 17px;
            color: black;
        }

        .table {
            color: black;
        }

    </style>

    <div class="top">
        <h4 style="margin-bottom:20px">Assignment marks for ;):</h4>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Subject</th>
                    <th scope="col">Grade</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Flag</td>
                    <td>{{ flag }}</td>
                </tr>
            </tbody>
        </table>
    </div>

{% endblock %}

downUnderCTF/grades/grades_grades_grades/src/templates/grades.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .top {
            top: 0;
            padding-left:  30px;
            padding-top: 40px;
            padding-bottom: 30px
        }

        .bottom {
            top: 0;
            text-align: center;
            padding-left:  30px;
            padding-top: 40px;
            padding-bottom: 30px;
            padding-right:  30px;
        }

        .h1 {
            font-size: 60px;
            margin-bottom: 60px;
        }

        .user_info {
            font-size:18px;
            padding-left: 17px;
            color: black;
        }

        .table {
            color: black;
        }

    </style>

    <div class="top">
        <h4 style="margin-bottom:20px">Logged in user info:</h4>
        <p class="user_info"><strong style="font-weight: bold;">Student Number:</strong> {{ number }}<p>
        <p class="user_info"><strong style="font-weight: bold;">Student Email:</strong> {{ email }}</p>
        <p class="user_info"><strong style="font-weight: bold;">Student Role:</strong> {{ role }}</p>
    </div>

    <div class="bottom">
        <h4 style="margin-bottom:20px">Assignment marks for {{ number }}:</h4>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Subject</th>
                    <th scope="col">Grade</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Maths</td>
                    <td>{{ mg }}</td>
                </tr>
                <tr>
                    <td>English</td>
                    <td>{{ eg }}</td>
                </tr>
                <tr>
                    <td>Science</td>
                    <td>{{ sg }}</td>
                </tr>
                <tr>
                    <td>Geography</td>
                    <td>{{ gg }}</td>
                </tr>
                <tr>
                    <td>Art</td>
                    <td>{{ ag }}</td>
                </tr>
            </tbody>
        </table>
    </div>

{% endblock %}

downUnderCTF/grades/grades_grades_grades/src/templates/public.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .top {
            top: 0;
            text-align: center;
            padding-top: 40px;
            padding-bottom: 70px
        }

        .h1 {
            font-size: 60px;
            margin-bottom: 60px;
        }

    </style>

    <div class="top">
        <h1 class="h1">Check your assignment grades here!!</h1>
        <img src="https://www.thoughtco.com/thmb/utWT4obdRRxLL5LDjB8ZpPCJUFo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/the-best-157314672-5a2ffaf8beba33003773ac96.jpg" height="700" width="700">
    </div>

{% endblock %}

downUnderCTF/grades/grades_grades_grades/src/templates/signup.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .text-center {
            width: 30%;
            text-align: center;
            margin-top: 20px;
            margin-left: auto;
            margin-right: auto;
        }

        .text-center a {
            font-family: Trebuchet MS Serif;
            font-color: blue;
            margin-top: 10px;
        }

        .top {
            top: 0;
            text-align: center;
            background-color: #DDDDDD;
            padding-top: 50px;
            padding-bottom: 40px;
        }

        .hl {
            font-size: 50px;
        }

        .bottom {
            margin-bottom: 20px;
        }

    </style>

    <div class="top">
        <h1 class="hl">Sign up</h1>
    </div>

    <div class="text-center">
        <form class="form-login" method="post">
            <fieldset>
                <legend style="margin-bottom: 20px">Create a new account to view grades:</legend>

                <div class="form-group">
                    <label for="Username" class="spacing">Enter your student number:</label>
                    <input type="text" class="form-control" id="stu_num" name="stu_num" placeHolder="Username"

                           required autofocus>
                </div>

                <div class="form-group">
                    <label for="Email" class="spacing">Confirm your student email:</label>
                    <input type="email" class="form-control" id="stu_email" name="stu_email" placeHolder="Email" required

                           autofocus>
                </div>

                <div class="form-group">
                    <label for="Password" class="spacing">Enter a password:</label>
                    <input type="password" class="form-control" id="password" name="password" placeHolder="Password"

                           required autofocus>
                </div>

                <button type="submit" class="btn btn-primary" style="margin-bottom: 20px">Submit</button>

            </fieldset>
        </form>
    </div>

{% endblock %}